### ISSUE TITLE
position control on yaw direction?

### ISSUE THREAD

**Issue by JoeyZhu** [SuperRoach/GimbalArduinoController#1]
I bought a mini3d, but position control on yaw did not work properly. 

Can you make position control on both yaw and pitch ? What's the firmware version are you using?

**Comment by SuperRoach** [comment]
The code in there locks it down to controlling one at a time, but depending on the mode you do have control of two axis at once and can totally do it. It'd recommend having another Dial/Poto wired up to make use of it though! The firmware seemed pretty similar on the mini3d, 1.35 possibly? I havn't been in it for a while. it wasn't the newest one.

**Comment by JoeyZhu** [comment]
precision is too low for mini3d. I bought two busmotor and build a gimble by myself. yaw and pitch has 12 bits precision and has absolute position feedback. Just need to send serial to motor driver to control its position. Thank you!

**Comment by SuperRoach** [comment]
Absolute position would make it be awesome! I could only find relative positioning based on the manual.

If you were to use this code still, the dial could be used to increment an internal value, which is then the absolute position you want to send to the yaw/pitch OR, the pot dial could be read and divided to the correct value to deal with.
